config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :cars
      resources :booking, only: [:create]
    end
  end

  resources :users, only: [:show]
  resource :text
  resource :admin, except: [:edit, :new, :create] do
    member do
      get 'cars'
      get 'new_car'
      get 'upload_photos'
      get 'edit_car'
      get 'text_main'
      get 'text_other'
      get 'text_metatags'
    end
  end

  resources :cars, except: [:edit] do
    resources :photos, only: [:create, :destroy] do
      member do
        patch :toggle_main_photo
      end
    end
    resources :reservations, only: [:create]
  end
  resources :quick_bookings, only: [:create]
  resources :bookings, only: [:create, :show, :index, :new] do
    resources :documents, only: [:create]
  end
  resources :reviews, only: [:create, :index, :destroy, :approve] do
    member do
      post '/approve' => "reviews#approve"
    end
  end
  resources :prices
  resources :contacts, only: [:index, :create]
  resources :terms, only: [:index]
  resources :faqs, only: [:index]
  resources :abouts, only: [:index]
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord

  include ActionView::Helpers::AssetUrlHelper

  # before_validation :parse_image
  # attr_accessor :image_base

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_attached_file :prava, styles: { medium: "300x300>" }
  validates_attachment_content_type :prava, content_type: /\Aimage\/.*\z/

  # has_many_attached :documents

  default_scope {order('created_at DESC')}

  def picture_url
    "http://amigorent.ru" + self.picture.url
  end

  def prava_url
    "http://amigorent.ru" + self.prava.url
  end

  def cover_avatar(size)
    if self.avatar
      self.avatar.url(size)
    else
      "blank.jpg"
    end
  end

  def cover_prava(size)
    if self.prava
      self.prava.url(size)
    else
      "blank.jpg"
    end
  end

  def send_sms
    message = MainsmsApi::Message.new(message: "#{self.firstname} авто: #{self.car} тел: #{self.phone} с #{self.start_date} до #{self.end_date}", recipients: ['79217101615'])
    response = message.deliver
  end

  private
    def parse_image
      image = Paperclip.io_adapters.for(image_base)
      image.original_filename = "file.jpg"
      self.picture = image
    end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  default_scope {order('sort')}

  

  def cover_photo(size)
    if self.photos.where(main_photo: true).length > 0
      self.photos.where(main_photo: true)[0].image.url(size)
      # self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true
      validates :name, presence: true
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :car

  has_attached_file :image, styles: { main: "340x200#", list: "470x300#", prices: "150x100>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/quick_booking.rb
class QuickBooking < ApplicationRecord
  validates :name, presence: true
  validates :contacts, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  def send_sms
    message = MainsmsApi::Message.new(message: "Новая заявка от #{self.name},#{self.contacts},с #{self.start_date.strftime("%d-%m-%Y")} до #{self.end_date.strftime("%d-%m-%Y")} кузов: #{('Седан' if self.is_sedan) || ('Хетчбэк' if self.is_hatch) || ('Кроссовер' if self.is_cross) || ('Минивен' if self.is_minivan) || ('Универсал' if self.is_universal)}", recipients: ['79217101615'])
    response = message.deliver
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :car
end

app/models/review.rb
class Review < ApplicationRecord
  default_scope {order('created_at DESC')}
end

app/models/term.rb
class Term < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, presence: true, length: {maximum: 50}
  validates :lastname, presence: true, length: {maximum: 50}

  has_many :cars
  has_many :bookings

end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/text_helper.rb
module TextHelper
end

app/views/admins/_left_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar -->
  <div class="sidebar">
    <!-- sidebar menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <% if current_page?(cars_admin_path) || current_page?(controller: 'admins', action: 'edit_car') %>
        <li class="treeview active">
      <% else %>
        <li class="treeview">
      <% end %>
         <a href="#"> <i class="icon-home"></i> <span>Автомобили</span>
           <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i>
           </span>
         </a>
        <ul class="treeview-menu">
          <% if current_page?(cars_admin_path) %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
            <%= link_to cars_admin_path do %>
              <i class="fa fa-angle-right"></i> Список авто
            <% end %>
            <%= link_to new_car_admin_path do %>
              <i class="fa fa-angle-right"></i> Добавить новый авто
            <% end %>
          </li>
        </ul>
      </li>

      <% if current_page?(text_main_admin_path) || current_page?(text_other_admin_path) %>
        <li class="treeview active">
      <% else %>
        <li class="treeview">
      <% end %>
        <a href="#"> <i class="icon-home"></i>
          <span>Редактирование текста</span>
          <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <% if current_page?(text_main_admin_path) %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
            <%= link_to text_main_admin_path do %>
              <i class="fa fa-angle-right"></i> Главная страница
            <% end %>
          </li>
          <% if current_page?(text_other_admin_path) %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
            <%= link_to text_other_admin_path do %>
              <i class="fa fa-angle-right"></i> Остальные страницы
            <% end %>
            <% if current_page?(text_metatags_admin_path) %>
            <li class="active">
          <% else %>
            <li>
          <% end %>
            <%= link_to text_metatags_admin_path do %>
              <i class="fa fa-angle-right"></i> Метатеги
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview"> <a href="#"> <i class="icon-home"></i> <span>Заявки</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
        <ul class="treeview-menu">
          <li class="active"><a href="index.html"><i class="fa fa-angle-right"></i> Заявки большие</a></li>
          <li><a href="index-crm.html"><i class="fa fa-angle-right"></i> Заявки маленькие</a></li>
        </ul>
      </li>
      <li class="treeview"> <a href="#"> <i class="icon-home"></i> <span>Пользователи</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
        <ul class="treeview-menu">
          <li class="active"><a href="index.html"><i class="fa fa-angle-right"></i> Все пользователи</a></li>
        </ul>
      </li>
    </ul>
  </div>
  <!-- /.sidebar -->
</aside>

app/views/admins/cars.html.erb
<%= render 'header' %>
<%= render 'left_sidebar' %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header sty-one">
      <h1>Список автомобилей</h1>
      <ol class="breadcrumb">
        <li>
          <%= link_to "Главная", admin_path %>
        </li>
        <li><i class="fa fa-angle-right"></i> Список автомобилей</li>
      </ol>
    </div>

    <!-- Main content -->
    <div class="content">
      <div class="row">
        <%= render "cars"  %>
      </div>
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <%= render 'footer'  %>
<!-- ./wrapper -->

app/views/admins/edit_car.html.erb
<%= render 'header' %>
<%= render 'left_sidebar' %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header sty-one">
      <h1>Редактирование <%= @car.car_name %></h1>
      <ol class="breadcrumb">
        <li>
          <%= link_to 'Главная', admin_path %>
        </li>
        <li><i class="fa fa-angle-right"></i> <%= link_to 'Автомобили', cars_admin_path %></li>
        <li><i class="fa fa-angle-right"></i> <%= @car.car_name %></li>
      </ol>
    </div>
    <!-- :car_name, :year, :color, :transmission, :is_air, :engine_capacity, :is_electropackage, :car_class, :car_type, :price_1, :price_2, :price_3, :price_4, :price_5, :old_price_1, :old_price_2, :old_price_3, :old_price_4, :old_price_5, :price_hour, :price_main, :deposit, :description, :fuel, :number_doors, :active, :sort, :show_on_main -->

    <!-- Main content -->
    <div class="content">
      <div class="row">
        <%= form_for @car do |f| %>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <h4 class="text-black">Цены</h4>
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">1 сутки</th>
                        <th scope="col">4-7 суток</th>
                        <th scope="col">8-14 суток</th>
                        <th scope="col">15-30 суток</th>
                        <th scope="col">> 30 суток</th>
                        <th scope="col">За час</th>
                        <th scope="col">Залог</th>
                        <th scope="col">На главной</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><%= f.text_field :price_1, placeholder: "1000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_2, placeholder: "1000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_3, placeholder: "1000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_4, placeholder: "1000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_5, placeholder: "1000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_hour, placeholder: "150", class: "form-control", required: true %></td>
                        <td><%= f.text_field :deposit, placeholder: "3000", class: "form-control", required: true %></td>
                        <td><%= f.text_field :price_main, placeholder: "от 1000 руб", class: "form-control", required: true %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="text-center">
                  <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
                </div>
                <hr>
                <h4 class="text-black">Старые цены</h4>
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">1 сутки</th>
                        <th scope="col">4-7 суток</th>
                        <th scope="col">8-14 суток</th>
                        <th scope="col">15-30 суток</th>
                        <th scope="col">> 30 суток</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td><%= f.text_field :old_price_1, class: "form-control" %></td>
                        <td><%= f.text_field :old_price_2, class: "form-control" %></td>
                        <td><%= f.text_field :old_price_3, class: "form-control" %></td>
                        <td><%= f.text_field :old_price_4, class: "form-control" %></td>
                        <td><%= f.text_field :old_price_5, class: "form-control" %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="text-center">
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
              <br>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div class="click2edit m-b-3">
                  <h4>Название авто</h4>
                  <%= f.text_field :car_name, id: "summernote", class: "", style: "min-width: 800px;", rows: "1" %>
                </div>
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div class="click2edit m-b-3">
                  <h4>Год</h4>
                  <%= f.text_field :year, id: "summernote", class: "", style: "min-width: 800px;", rows: "1" %>
                </div>
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div class="click2edit m-b-3">
                  <h4>Цвет</h4>
                  <%= f.text_field :color, id: "summernote", class: "", style: "min-width: 800px;", rows: "1" %>
                </div>
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div>
                  <div class="form-group">
                    <div class="form-group">
                      <h4 class="text-black">Кузов </h4>
                    </div>
                    <%= f.select :car_type, [["Седан", "Седан"], ["Хэтчбек", "Хэтчбек"], ["Универсал", "Универсал"], ["Купе", "Купе"], ["Кроссовер", "Кроссовер"]], {}, {class:"form-control", id: "car_type"} %>
                  </div>
                </div>

                <div class="">
                  <div class="form-group">
                    <div class="form-group">
                      <h4 class="text-black">Класс </h4>
                    </div>
                    <%= f.select :car_class, [["Эконом", "Эконом"], ["Средний", "Средний"], ["Бизнес", "Бизнес"], ["Коммерческий", "Коммерческий"]], {}, {class:"form-control", id: "car_class"} %>
                  </div>
                </div>

                <div class="">
                  <div class="form-group">
                    <div class="form-group">
                      <h4 class="text-black">Коробка</h4>
                    </div>
                    <%= f.select :transmission, [["Автомат", "Автомат"], ["Механика", "Механика"], ["Вариатор", "Вариатор"], ["Робот", "Робот"]], {}, {class:"form-control", id: "transmission"} %>
                  </div>
                </div>

                <div class="">
                  <div class="form-group">
                    <div class="form-group">
                      <h4 class="text-black">Двери</h4>
                    </div>
                    <%= f.select :number_doors, [["2", 2], ["3", 3], ["4", 4], ["5", 5]], {}, {class:"form-control", id: "number_doors"} %>
                  </div>
                </div>
                <div class="">
                  <div class="form-group">
                    <div class="form-group">
                      <h4 class="text-black">Топливо</h4>
                    </div>
                    <%= f.select :fuel, [["Бензин", "Бензин"], ["Дизель", "Дизель"]], {}, {class:"form-control", id: "fuel"} %>
                  </div>
                </div>
                <div>
                  <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
                </div>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-4 form-group">
                    <h4 class="text-black">Объём двигателя </h4>
                    <%= f.text_field :engine_capacity, placeholder: "Объём двигателя?", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="row form-group">
                  <div class="col-md-4">
                    <%= f.check_box :is_air %> Есть кондиционер?
                  </div>
                  <div class="col-md-4">
                    <%= f.check_box :is_electropackage %> Есть электропакет?
                  </div>
                </div>
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
          <div class="col-12">
            <div class="card m-t-3">
              <div class="card-body">
                <div class="col-md-12 form-group">
                  <label>Порядковый номер (для сортировки)</label>
                  <%= f.text_field :sort, placeholder: "Номер", class: "form-control", required: true %>
                </div>
                <div class="col-md-12 form-group">
                  <label>Показывать на главной?</label>
                  <%= f.check_box :show_on_main %>
                </div>
                <div class="col-md-12 form-group">
                  <label>Описание</label>
                  <%= f.text_area :description, rows: 10, placeholder: "Описание авто", class: "form-control", required: true %>
                </div>
                <%= f.submit "Сохранить", class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
        <% end %>

          <div class="card m-t-3">
            <div class="card-body">
              <!-- PHOTOS UPLOAD GOES HERE -->
              <%= form_for @car, url: car_photos_path(@car), method: 'post', html: {multipart: true} do |f| %>

                  <h4 class="text-black text-center">Фото </h4>
                  <div id="photos">
                    <% if @photos.count > 0 %>
                        <% @photos.each do |photo| %>
                          <%= image_tag photo.image.url(:medium), class: "m-t-1" %>
                            <%= link_to car_photo_path(photo.car_id, photo), remote: true, method: :delete, data: {confirm: "Уверен?"} do %>
                              <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
                            <% end %>
                            <%= link_to toggle_main_photo_car_photo_path(photo.car_id, photo), remote: true, method: :patch, data: {confirm: "Главное фото?"} do %>
                              <% if photo.main_photo %>
                                <i class="fa fa-times fa-lg" aria-hidden="true"></i>
                              <% else %>
                                <i class="fa fa-check fa-lg" aria-hidden="true"></i>
                              <% end %>
                              
                            <% end %>
                        <% end %>
                    <% end %>
                  </div>
                  <br>
                  <div class="form-group text-center" >
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Выберите фото
                      <%= file_field_tag "image[]", type: :file, multiple: true %>
                    </span>
                  </div>
                <div class="text-center m-b-3">
                  <%= f.submit "Загрузить фото", class: "btn btn-rounded btn-outline-danger" %>
                </div>
              <% end %>
            </div>
          </div>
      </div>
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <%= render 'footer'  %>
<!-- ./wrapper -->

app/views/admins/upload_photos.html.erb
<%= render 'header' %>
<%= render 'left_sidebar' %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header sty-one">
      <h1>Добавление автомобиля</h1>
      <ol class="breadcrumb">
        <li>
          <%= link_to 'Главная', admin_path %>
        </li>
        <li><i class="fa fa-angle-right"></i> <%= link_to 'Автомобили', cars_admin_path %></li>
        <li><i class="fa fa-angle-right"></i> Новая машина</li>
      </ol>
    </div>
    <!-- :car_name, :year, :color, :transmission, :is_air, :engine_capacity, :is_electropackage, :car_class, :car_type, :price_1, :price_2, :price_3, :price_4, :price_5, :old_price_1, :old_price_2, :old_price_3, :old_price_4, :old_price_5, :price_hour, :price_main, :deposit, :description, :fuel, :number_doors, :active, :sort, :show_on_main -->

    <!-- Main content -->
    <div class="content">
      <div class="row">
          <div class="card m-t-3">
            <div class="card-body">
              <!-- PHOTOS UPLOAD GOES HERE -->
              <div id="photos">
                <% if @photos.count > 0 %>
                    <% @photos.each do |photo| %>
                      <%= image_tag photo.image.url(:medium), class: "m-t-1" %>
                        <%= link_to car_photo_path(photo.car_id, photo), remote: true, method: :delete, data: {confirm: "Уверен?"} do %>
                          <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
                        <% end %>
                    <% end %>
                <% end %>
              </div>
              <br>
              <%= form_for @car, url: car_photos_path(@car), method: 'post', html: {multipart: true} do |f| %>
                <h4 class="text-black text-center">Фото </h4>
                <div class="form-group text-center" >
                  <span class="btn btn-default btn-file text-babu">
                    <i class="fa fa-cloud-upload" aria-hidden="true"></i> Выберите фото
                    <%= file_field_tag "image[]", type: :file, multiple: true %>
                  </span>
                </div>
                <div class="text-center m-b-3">
                  <%= f.submit "Загрузить фото", class: "btn btn-rounded btn-outline-danger" %>
                </div>
              <% end %>
            </div>
          </div>
      </div>
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <%= render 'footer'  %>
<!-- ./wrapper -->

app/views/shared/_footer.html.erb
<% if !current_page?("/admin") %>
  <footer class="row site-footer">
    <div class="bottom-footer row m0">
      <div class="container">
        <div class="row">
          <%= link_to 'Главная', root_path %> | <%= link_to 'Автомобили', cars_path %> | <%= link_to 'Цены', prices_path %> | <%= link_to 'О нас', abouts_path %><br>
          <%= @footer_text.html_safe  %>
          <!-- г. Калининград, ул.А. Невского 36В, © 2010-2018. Автопрокат Амиго. Все права защищены. -->
        </div>
      </div>
    </div>
  </footer>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_page?(root_path) || current_page?(cars_path) || current_page?("/cars/#{params[:id]}") || current_page?(new_booking_path) || current_page?(reviews_path) || current_page?(prices_path) || current_page?(contacts_path) || current_page?(terms_path) || current_page?(abouts_path) || current_page?(faqs_path) %>
  <!--Top Bar-->
  <% if current_page?(root_path) %>
    <section class="row top-bar">
      <h2 class="hd-sec">Heading</h2>
    	<div class="container">
    		<div class="welcome-texts"><%= @main_up_text.html_safe %></div>
    		<ul class="social-lists-wSearch nav nav-pills">
    			<!-- <li><a href="#"><i class="ion-social-facebook"></i></a></li> -->
    		</ul>
    	</div>
    </section>
  <% end %>
    <!--Info Bar-->
  	<section class="row info-bar">
  		<div class="container">
  			<div class="row">
  				<div class="col-sm-3 col-xs-8 logo-box">
  					<a href="/" class="logo"><img src="/images/logo.png" alt=""></a>
  				</div>
  				<div class="col-sm-9 col-xs-4 info-box">
  					<div class="header-informations hidden-xs">
  						<div class="media info-media">
  							<div class="media-left"><i class="ion-location"></i></div>
  							<div class="media-body">
  								<h5 class="this-top text-center">Невского 36В, 3 этаж</h5>
  								<h5 class="this-bottom text-center">Калининград</h5>
  							</div>
  						</div>
  						<div class="media info-media">
  							<div class="media-left"><i class="ion-ios-telephone"></i></div>
  							<div class="media-body">
  								<h5 class="this-top text-center">(4012) 52-16-15</h5>
  								<h5 class="this-bottom text-center">amigorent@ya.ru</h5>
  							</div>
  						</div>
  						<div class="media info-media">
  							<div class="media-left"><i class="ion-ios-clock"></i></div>
  							<div class="media-body">
  								<h5 class="this-top text-center">Пн - Вс:</h5>
  								<h5 class="this-bottom text-center">09:00 ~ 19:00</h5>
  							</div>
  						</div>
  					</div>
  					<div class="cart-nav">
  						<a href="#" class="nav-hider hidden-md hidden-lg hidden-xs hidden-sm"><i class="ion-android-menu"></i></a>
  						<button type="button" class="navbar-toggle nav-hider collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
  							<span class="sr-only">Toggle navigation</span>
  							<i class="ion-android-menu"></i>
  						</button>
  					</div>
  				</div>
  			</div>
  		</div>
  	</section>
    <nav class="navbar navbar-default main-navigation navbar-static-top">
  		<div class="container">
  			<!-- Collect the nav links, forms, and other content for toggling -->
  			<div class="collapse navbar-collapse" id="main-nav">
  				<ul class="nav navbar-nav">
  					<li><%= link_to "Главная", root_path %></li>
  					<li><%= link_to "Автомобили", cars_path %></li>
  					<li><%= link_to "Цены", prices_path %></li>
  					<li><%= link_to "Контакты", contacts_path %></li>
            <li><%= link_to "Заказать", new_booking_path %></li>
  					<li><%= link_to "Отзывы", reviews_path %></li>
  					<li><%= link_to "Условия", terms_path %></li>
  					<li><%= link_to "FAQ", faqs_path %></li>
            <li><%= link_to "О нас", abouts_path %></li>
  				</ul>
  			</div><!-- /.navbar-collapse -->
  		</div><!-- /.container-fluid -->
  	</nav>
<% elsif request.path.include?('admin') %>

<% else %>
  <nav class="navbar navbar-default navbar-static-top" style="margin-bottom: 0px">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Амиго", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <button class="btn btn-form btn-small">
              <%= link_to "Добавить авто", new_car_path, style: "color: white; text-decoration: none;" %>
            </button>
          </li>

          <% if !user_signed_in? %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Manage Listings", cars_path %></li>
                <li><%= link_to "List Your Space", new_car_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>

        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
<% end %>