config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :cars
      resources :booking, only: [:create]
    end
  end

  resources :users, only: [:show]
  resource :text
  resource :admin, except: [:edit, :new, :create] do
    member do
      get 'cars'
      get 'new_car'
      get 'upload_photos'
      get 'edit_car'
      get 'text_main'
      get 'text_other'
      get 'text_metatags'
    end
  end

  resources :cars, except: [:edit] do
    resources :photos, only: [:create, :destroy] do
      member do
        patch :toggle_main_photo
      end
    end
    resources :reservations, only: [:create]
  end
  resources :quick_bookings, only: [:create]
  resources :bookings, only: [:create, :show, :index, :new] do
    resources :documents, only: [:create]
  end
  resources :reviews, only: [:create, :index, :destroy, :approve] do
    member do
      post '/approve' => "reviews#approve"
    end
  end
  resources :prices
  resources :contacts, only: [:index, :create]
  resources :terms, only: [:index]
  resources :faqs, only: [:index]
  resources :abouts, only: [:index]
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  default_scope {order('sort')}

  

  def cover_photo(size)
    if self.photos.where(main_photo: true).length > 0
      self.photos.where(main_photo: true)[0].image.url(size)
      # self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < ApiController

    before_action :set_car, only: [:show, :update]
    before_action :set_cars, only: [:index]

    def show
        render json: @car
    end

    def index
        render json: @cars
    end

    def create
        car = Car.new(car_params)
        if car.save
            render json: car, adapter: :json, status: 201
        else
            render json: { error: car.errors }, status: 422
        end
    end

    def update
        if @car.update(car_params)
            render json: @car, adapter: :json, status: 200
        else
            render json: { error: @car.errors }, status: 422
        end
    end

    private
        def set_car
            @car = Car.find(params[:id])
        end
        def set_cars
            @cars = Car.all
        end
        def car_params
            params.require(:car).permit(:car_name, :year, :color, :transmission, :is_air, :engine_capacity, :is_electropackage, :car_class, :car_type, :price_1, :price_2, :price_3, :price_4, :price_5, :old_price_1, :old_price_2, :old_price_3, :old_price_4, :old_price_5, :price_hour, :price_main, :deposit, :description, :fuel, :number_doors, :active, :sort, :show_on_main)
        end
  end

app/controllers/car_controller.rb
class CarController < ApplicationController
  before_action :set_car, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  def index
    @cars = current_user.cars
  end

  def new
    @car = current_user.cars.build
  end

  def create
    @car = current_user.cars.build(car_params)
    if @car.save
      redirect_to listing_car_path(@car), notice: "Сохранено"
    else
      render :new, notice: "Что то пошло не так!"
    end
  end

  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def update
    if @car.update(car_params)
      flash[:notice] = "Сохранено"
    else
      flash[:notice] = "Что то не так!"
    end
    redirect_back(fallback_location: request.referer)
  end

  private
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:car_name, :year, :color, :transmission, :is_air, :engine_capacity, :is_electropackage, :car_class, :car_type, :price_1, :price_2, :price_3, :price_4, :price_main, :deposit, :description, :active)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :update, :destroy]
  before_action :set_photos, only: [:photo_upload, :show]

  def index
    @cars = Car.all
    @footer_text = Text.first.footer_text
    @cars_title = Text.first.cars_title
    @cars_description = Text.first.cars_description
  end

  def new
    @car = current_user.cars.build
  end

  def create
    @car = current_user.cars.build(car_params)
    if @car.save
      redirect_to cars_admin_path, notice: "Сохранено"
    else
      redirect_back(fallback_location: request.referer, alert: "Что то не так!")
    end
  end

  def destroy
    if @car.destroy
      redirect_to root_path, notice: "Удалено"
    else
      flash[:alert] = "Что то не так!"
    end
  end

  def show
    @photos = @car.photos
    @footer_text = Text.first.footer_text
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def update
    new_params = car_params
    new_params = car_params.merge(active: true) if is_ready_car

    if @car.update(new_params)
      flash[:notice] = "Сохранено"
    else
      flash[:notice] = "Что то не так!"
    end
    redirect_back(fallback_location: request.referer)
  end

  private

    def set_car
      @car = Car.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "У вас нет прав на просмотр данной страницы!" unless current_user.id == @car.user_id || current_user.is_admin
    end

    def is_ready_car
      !@car.active && !@car.price_1.blank? && !@car.price_2.blank? && !@car.price_3.blank? && !@car.price_4.blank? && !@car.price_5.blank? && !@car.price_hour.blank? && !@car.price_main.blank? && !@car.car_name.blank? && !@car.photos.blank?
    end

    def set_photos
      @photos = @car.photos
    end

    def car_params
      params.require(:car).permit(:car_name, :year, :color, :transmission, :is_air, :engine_capacity, :is_electropackage, :car_class, :car_type, :price_1, :price_2, :price_3, :price_4, :price_5, :old_price_1, :old_price_2, :old_price_3, :old_price_4, :old_price_5, :price_hour, :price_main, :deposit, :description, :fuel, :number_doors, :active, :sort, :show_on_main)
    end
end

app/helpers/car_helper.rb
module CarHelper
end

app/views/cars/_car_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Основное", listing_car_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Цены", pricing_car_path, class: "sidebar-link active" %>
    <% if !@car.price_1.blank? && !@car.price_2.blank? && !@car.price_3.blank? && !@car.price_4.blank? && !@car.price_main.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Описание", description_car_path, class: "sidebar-link active" %>
    <% if !@car.car_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_car_path, class: "sidebar-link active" %>
    <% if !@car.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Всякое", amenities_car_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to 'Дата окончания цен', edit_price_path(price_id: 1), class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
</ul>
<hr/>
<% is_ready = !@car.price_1.blank? && !@car.price_2.blank? && !@car.price_3.blank? && !@car.price_4.blank? && !@car.price_main.blank? && !@car.car_name.blank? && !@car.photos.blank?  %>
<% is_active = @car.active %>
<%= form_for @car do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Опубликовать", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>
<br>
<%= form_for @car do |f| %>
  <%= f.hidden_field :active, value: false %>
  <%= f.submit "Снять с публикации", id: "unpublish_button", class: "btn btn-normal btn-block", disabled: !is_active %>
<% end %>
<br>
<%= link_to car_path(@car), remote: true, method: :delete, data: {confirm: "Уверены?"} do %>
  <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
<% end %>

app/views/cars/_cars_list.html.erb
<% @cars.each do |car| %>
  <% if car.active %>
  <!-- Add sale-offer  to down div-->
    <div class="media fleet fleet-list">
    <div class="row">
      <div class="col-md-5 col-sm-12 col-xs-12">
        <div class="media-left">
          <%= link_to car_path(car) do %>
            <%= image_tag car.cover_photo(:list), alt: "#{car.car_name}", title: "#{car.car_name}" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-7 col-sm-12 col-xs-12">
        <div class="media-body this-body">
          <div class="media this-header">
            <div class="media-body">
              <div class="row m0">
                <h2 class="rent">от <%= car.price_main %><sub>/сутки</sub></h2>
              </div>
              <h4 class="vehicle-title">
                <%= car.car_name %>
              </h4>
            </div>
            <div class="media-right">
              <%= link_to car_path(car), class:"detail-btn btn" do %>
                <span>подробнее</span><span><i class="ion-flash"></i></span>
              <% end %>
            </div>
          </div>
          <div class="summary row m0">
            <%= truncate car.description, length: 160 %>
          </div>
          <div class="row specification">
            <ul class="nav">
              <li><span><img src="/images/icons/fleet2/transmission.png" style="width: 20px;" alt="Коробка передач" title="Коробка передач"></span><%= car.transmission %></li>
              <li><span><img src="/images/icons/fleet2/fuel.png" style="width: 20px;" alt="Вид топлива" title="Вид топлива"></span><%= car.fuel %></li>
              <li><span><img src="/images/icons/fleet2/year.png" style="width: 20px;" alt="Год выпуска" title="Год выпуска авто"></span><%= car.year %></li>
              <li><span><img src="/images/icons/fleet2/car_type.png" style="width: 20px;" alt="Тип кузова" title="Тип кузова автомобиля"></span><%= car.car_type %></li>
              <li><span><img src="/images/icons/fleet2/capacity.png" style="width: 20px;" alt="Объем двигателя" title="Объем двигателя"></span><%= car.engine_capacity %></li>
              <li>
                <% if car.is_air %>
                <span><img src="/images/icons/fleet2/snow.png" style="width: 20px;" alt="Кондиционер" title="Есть кондиционер"></span> Кондиционер
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/cars/_single_car_main.html.erb
<% counter = 0 %>
<% @cars.each do |car| %>
  <% if car.show_on_main %>
    <% counter += 1 %>
    <% if counter <=3 %>
    <div class="col-md-4 fleet fleet2 ">
    <% else %>
    <div class="col-md-4 fleet fleet2 hidden-xs hidden-sm">
    <% end %>
      <div class="inner row" style="border-radius:20px;">
        <h2 class="rent text-center"><small>от</small><%= car.price_main %><sub>/сутки</sub></h2>
        <h4 class="vehicle-title text-center"><%= car.car_name %></h4>
        <div class="row vehicle-img text-center">
          <%= link_to car_path(car) do %>
            <%= image_tag car.cover_photo(:main), alt: "#{car.car_name}", title: "#{car.car_name}", class:"car-list-main" %>
          <% end %>
        </div>
        <div class="row specification">
          <div>
            <table class="table text-center" >
              <tr>
                <td  style="display:inline-block;"><img src="/images/icons/fleet2/transmission.png" style="width: 15px;" alt="Коробка передач" title="Коробка передач"> <%= car.transmission %></td>
                <td  style="display:inline-block;"><img src="/images/icons/fleet2/fuel.png" style="width: 15px;" alt="Вид топлива" title="Вид топлива"> <%= car.fuel %></td>
                <td style="display:inline-block;"><img src="/images/icons/fleet2/year.png" style="width: 15px;" alt="Год выпуска" title="Год выпуска авто"> <%= car.year %></td>
              </tr>
              <tr>
                <td style="display:inline-block;"><img src="/images/icons/fleet2/car_type.png" style="width: 15px;" alt="Тип кузова" title="Тип кузова автомобиля"> <%= car.car_type %></td>
                <td style="display:inline-block;"><img src="/images/icons/fleet2/capacity.png" style="width: 15px;" alt="Объем двигателя" title="Объем двигателя"> <%= car.engine_capacity %></td>
                <td style="display:inline-block;">
                  <% if car.is_air %>
                    <img src="/images/icons/fleet2/snow.png" style="width: 15px;" alt="Кондиционер" title="Есть кондиционер"> Есть
                  <% else %>
                    <img src="/images/icons/fleet2/snow.png" style="width: 15px;" alt="Кондиционер" title="Нет кондиционера"> Нет
                  <% end %>
                </td>
              </tr>
            </table>
          </div>
          <%= link_to "+", car_path(car), class: "details-page" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/cars/index.html.erb
<% title @cars_title %>
<% description @cars_description %>
<!--Page Cover-->
	<section class="row page-cover">
		<div class="container">
			<h2 class="h1 page-title">Автомобили</h2>
			<ol class="breadcrumb">
				<li><%= link_to 'Главная', root_path %></li>
				<li class="active">Автомобили</li>
			</ol>
		</div>
	</section>
	<section class="row wrapper-fleet">
		<div class="container">
			<%= render 'cars/cars_list' %>
		</div>
	</section>
<%= render 'shared/footer', cached: true %>

app/views/cars/show.html.erb
<% title 'Взять' + ' ' + @car.car_name + ' ' + 'в аренду' %>
<% description 'Взять' + ' ' + @car.car_name + ' ' + 'в аренду в автопрокате Амиго' %>
  <section class="row wrapper-car-details">
    <div class="container">
			<ol class="breadcrumb">
				<li><%= link_to 'Главная', root_path %></li>
				<li><%= link_to 'Автомобили', cars_path %></li>
        <li class="active"><%= @car.car_name %></li>
			</ol>
		</div>
  <div class="container">
  	<div class="row car-dt">
  		<div class="col-sm-12 col-md-8 col-xs-12 car-images fleet">
  			<div class="row m0 this-heading">
  				<h5 class="this-class"><%= @car.car_class.capitalize %></h5>
  				<h3 class="vehicle-title"><%= @car.car_name %></h3>
  			</div>
  			<div class="row m0 this-cover-image">
          <div class="item">
            <div class="clearfix" style="max-width:750px;">
                <ul id="image-gallery" class="gallery list-unstyled cS-hidden">
                  <% @photos.each do |photo| %>

                      <li data-thumb="<%= photo.image.url(:thumb) %>">
                        <%= image_tag photo.image.url(), alt: @car.car_name, title: @car.car_name %>
                       </li>

                  <% end %>
                </ul>
            </div>
          </div>
        </div>
        <%= link_to 'Назад', url_for(:back), class:"btn btn-normal" %>
  		</div>

  		<div class="col-sm-12 col-md-4 col-xs-12 car-infomations fleet">
  			<div class="row focus-infos">
  				<h4 class="this-heading">Спецификация</h4>
  				<p>Все данные об автомобиле.</p>
  			</div>
  			<ul class="focus-informations nav">
          <li><span><img src="/images/icons/fleet2/transmission-white.png" style="width: 20px;" alt="Коробка передач" title="Коробка передач"></span>  Коробка передач<span class="this-value"><%= @car.transmission %></span></li>
          <li><span><img src="/images/icons/fleet2/car_type-white.png" style="width: 20px;" alt="Цвет кузова" title="Цвет кузова"></span>  Цвет кузова <span class="this-value"><%= @car.color %></span></li>
          <li><span><img src="/images/icons/fleet2/fuel-white.png" style="width: 20px;" alt="Вид топлива" title="Вид топлива"></span>  Вид топлива <span class="this-value"><%= @car.fuel %></span></li>
          <li><span><img src="/images/icons/fleet2/year-white.png" style="width: 20px;" alt="Год выпуска" title="Год выпуска авто"></span>  Год выпуска <span class="this-value"><%= @car.year %></span></li>
          <li><span><img src="/images/icons/fleet2/capacity-white.png" style="width: 20px;" alt="Объем двигателя" title="Объем двигателя"></span>  Объём двигателя <span class="this-value"><%= @car.engine_capacity %></span></li>
          <li><span><img src="/images/icons/fleet2/car-type-white.png" style="width: 20px;" alt="Тип кузова" title="Тип кузова автомобиля"></span>  Тип кузова <span class="this-value"><%= @car.car_type %></span></li>
          <li><span><img src="/images/icons/fleet2/number-doors-white.png" style="width: 20px;" alt="Количество дверей" title="Количество дверей"></span>  Кол-во дверей <span class="this-value"><%= @car.number_doors %></span></li>
          <li>
            <% if @car.is_air %>
              <span><img src="/images/icons/fleet2/snow-white.png" style="width: 20px;" alt="Кондиционер" title="Есть кондиционер"></span> Кондиционер <span class="this-value">Есть</span>
            <% end %>
          </li>
          <li>
            <% if @car.is_electropackage %>
              <span><img src="/images/icons/fleet2/electro-white.png" style="width: 20px;" alt="Электропакет" title="Есть электропакет, стеклоподъемники и тд"></span> Электропакет <span class="this-value">Есть</span>
            <% end %>
          </li>
        </ul>
  		<div class="this-footer row m0">
  			<h3 class="rent text-center"><small>от</small><%= @car.price_5 %><sub>/сутки</sub></h3>
        <%= link_to "Забронировать", new_booking_path(car_id: @car.id), class:"hire-btn" %>
  		</div>
  	</div>
  	</div>
  <!-- Tab panes -->
  <div class="tab-content desctiption-contents">
  	<div class="tab-pane active">
      <table class="table table-bordered prices-single-car text-center">
        <thead>
          <h3>Цены</h3>
        </thead>
			  <tbody>
        <tr class="prices-single-car-header">
  				<td class="prices-table-header">до 3 суток</td>
  				<td class="prices-table-header">4-7 суток</td>
  				<td class="prices-table-header">8-14 суток</td>
  				<td class="prices-table-header">15-30 суток</td>
  				<td class="prices-table-header">> 30 суток</td>
          <td class="prices-table-header">Залог</td>
			  </tr>
					<tr>
            <td>
							<div><%= @car.price_1 %> рублей</div>
						</td>
					<td>
            <div><%= @car.price_2 %> рублей</div>
					</td>
					<td>
						<div><%= @car.price_3 %> рублей</div>
					</td>
					<td>
						<div><%= @car.price_4 %> рублей</div>
					</td>
					<td>
						<div><%= @car.price_5 %> рублей</div>
					</td>
          <td>
						<div><%= @car.deposit %> рублей</div>
					</td>
				</tr>
      </tbody>
      </table>
      <h3>Описание</h3>
  		<%= @car.description %>
  	</div>
  </div>
  </div>
  </section>
<%= render 'shared/footer', cached: true %>
<script>
	 $(document).ready(function() {
	$("#content-slider").lightSlider({
            loop:true,
            keyPress:true
        });
        $('#image-gallery').lightSlider({
            gallery:true,
            item:1,
            thumbItem:5,
            slideMargin: 0,
            vThumbWidth:100,
            speed:1000,
            auto:false,
            loop:true,
            onSliderLoad: function() {
                $('#image-gallery').removeClass('cS-hidden');
            }
        });
});
</script>