config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users, controllers: { confirmations: 'confirmations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :cars
      resources :booking, only: [:create]
    end
  end

  resources :users, only: [:show]
  resource :text
  resource :admin, except: [:edit, :new, :create] do
    member do
      get 'cars'
      get 'new_car'
      get 'upload_photos'
      get 'edit_car'
      get 'text_main'
      get 'text_other'
      get 'text_metatags'
    end
  end

  resources :cars, except: [:edit] do
    resources :photos, only: [:create, :destroy] do
      member do
        patch :toggle_main_photo
      end
    end
    resources :reservations, only: [:create]
  end
  resources :quick_bookings, only: [:create]
  resources :bookings, only: [:create, :show, :index, :new] do
    resources :documents, only: [:create]
  end
  resources :reviews, only: [:create, :index, :destroy, :approve] do
    member do
      post '/approve' => "reviews#approve"
    end
  end
  resources :prices
  resources :contacts, only: [:index, :create]
  resources :terms, only: [:index]
  resources :faqs, only: [:index]
  resources :abouts, only: [:index]
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord

  include ActionView::Helpers::AssetUrlHelper

  # before_validation :parse_image
  # attr_accessor :image_base

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_attached_file :prava, styles: { medium: "300x300>" }
  validates_attachment_content_type :prava, content_type: /\Aimage\/.*\z/

  # has_many_attached :documents

  default_scope {order('created_at DESC')}

  def picture_url
    "http://amigorent.ru" + self.picture.url
  end

  def prava_url
    "http://amigorent.ru" + self.prava.url
  end

  def cover_avatar(size)
    if self.avatar
      self.avatar.url(size)
    else
      "blank.jpg"
    end
  end

  def cover_prava(size)
    if self.prava
      self.prava.url(size)
    else
      "blank.jpg"
    end
  end

  def send_sms
    message = MainsmsApi::Message.new(message: "#{self.firstname} авто: #{self.car} тел: #{self.phone} с #{self.start_date} до #{self.end_date}", recipients: ['79217101615'])
    response = message.deliver
  end

  private
    def parse_image
      image = Paperclip.io_adapters.for(image_base)
      image.original_filename = "file.jpg"
      self.picture = image
    end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :reservations, dependent: :destroy
  default_scope {order('sort')}

  

  def cover_photo(size)
    if self.photos.where(main_photo: true).length > 0
      self.photos.where(main_photo: true)[0].image.url(size)
      # self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email, presence: true
      validates :name, presence: true
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :car

  has_attached_file :image, styles: { main: "340x200#", list: "470x300#", prices: "150x100>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/price.rb
class Price < ApplicationRecord
end

app/models/quick_booking.rb
class QuickBooking < ApplicationRecord
  validates :name, presence: true
  validates :contacts, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  def send_sms
    message = MainsmsApi::Message.new(message: "Новая заявка от #{self.name},#{self.contacts},с #{self.start_date.strftime("%d-%m-%Y")} до #{self.end_date.strftime("%d-%m-%Y")} кузов: #{('Седан' if self.is_sedan) || ('Хетчбэк' if self.is_hatch) || ('Кроссовер' if self.is_cross) || ('Минивен' if self.is_minivan) || ('Универсал' if self.is_universal)}", recipients: ['79217101615'])
    response = message.deliver
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :car
end

app/models/review.rb
class Review < ApplicationRecord
  default_scope {order('created_at DESC')}
end

app/models/term.rb
class Term < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, presence: true, length: {maximum: 50}
  validates :lastname, presence: true, length: {maximum: 50}

  has_many :cars
  has_many :bookings

end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.create(review_params)
    if verify_recaptcha(model: @review) && @review.save
      ReviewMailer.with(review: @review).review_email.deliver_later
      redirect_back(fallback_location: request.referer, notice: "Отзыв успешно создан! Он будет проверен на предмет рекламы и размещен.")
    else
      redirect_back(fallback_location: request.referer, alert: "Что то пошло не так!")
    end
  end

  def index
    @reviews = Review.all # Pagination!!!
    @reviews_text = Text.first.reviews_text
    @footer_text = Text.first.footer_text
    @reviews_title = Text.first.reviews_title
    @reviews_description = Text.first.reviews_description
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    @reviews = Review.all

    respond_to :js
  end

  def approve
    @review = Review.find(params[:id])
    @review.active = true
    @review.save
    redirect_back(fallback_location: request.referer, notice: "Отзыв одобрен!")
  end

  private
    def review_params
      params.require(:review).permit(:text, :star, :active, :name, :email)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/text_helper.rb
module TextHelper
end

app/views/reviews/_reviews_on_main.html.erb
<section class="row video-testimonial">
  <div class="container">
    <div class="row">
      <h2 class="text-center">Отзывы</h2>
  <div class="carousel-reviews broun-block">
        <div id="carousel-reviews" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% count = 0 %>
            <% @reviews.each do |review| %>
              <% if review.active? %>
                <% count += 1 %>
                <% if count == 1 %>
                  <div class="item active">
                <% end %>
                <% if count == 4 || count == 7 %>
                  <div class="item">
                <% end %>
                <% if count == 1 || count == 4 || count == 7 %>
                  <div class="col-md-4 col-sm-6">
                <% end %>
                <% if count == 2 || count == 5 || count == 8 %>
                  <div class="col-md-4 col-sm-6 hidden-xs">
                <% end %>
                <% if count == 3 || count == 6 || count == 9 %>
                  <div class="col-md-4 col-sm-6 hidden-sm hidden-xs">
                <% end %>
                    <div class="block-text rel zmin">
                      <h3 class="text-center" style="color:#f77d0a;"><%= review.name %></h3>
                      <p><%= truncate review.text, length: 300 %></p>
                      <ins class="ab zmin sprite sprite-i-triangle block"></ins>
                    </div>
                    <div class="person-text rel">
                    </div>
                  </div>
                  <% if count == 3 %>
                    </div>
                  <% end %>
                  <% if count == 6 %>
                    </div>
                  <% end %>
                  <% if count == 9 %>
                    </div>
                  <% end %>
              <% end %>
            <% end %>
          </div>
          <a class="left carousel-control" href="#carousel-reviews" role="button" data-slide="prev">
            <i class="glyphicon glyphicon-chevron-left" style="color:#f77d0a;font-size:20px;" aria-hidden="true"></i>
          </a>
          <a class="right carousel-control" href="#carousel-reviews" role="button" data-slide="next">
            <i class="glyphicon glyphicon-chevron-right" style="color:#f77d0a;font-size:20px;" aria-hidden="true"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/reviews/_single_review.html.erb
<ul class="media-list comment-list">
  <% @reviews.each do |review| %>
    <% if review.active || (current_user && current_user.is_admin) %>
      <li class="comment media">
        <div class="media-body">
        <h5 class="this-title"><%= review.name %>  <i><%= review.created_at.strftime("%d-%m-%Y") %></i>
          <% if current_user && current_user.is_admin %>
            <%= link_to review_path(review.id), remote: true, method: :delete, data: {confirm: "Уверен?"} do %>
              <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
            <% end %>
            <% if !(review.active?) %>
              <%= link_to approve_review_path(review), method: :post do %>
                <i class="fa fa-thumbs-up fa-lg"></i>
              <% end %>
            <% end %>
          <% end %>
        </h5>
        <p><%= review.text %></p>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/reviews/destroy.js.erb
$('.comment-list').html("<%= j render 'single_review' %>")

app/views/reviews/index.html.erb
<% title @reviews_title %>
<% description @reviews_description %>
<div class="container" style="margin-bottom: 10px;">
  <div class="col-md-8">
    <div class="row m0 comments-area">
    	<h2 class="this-area-title">Отзывы</h2>
      <h4 class="this-sub-title"><%= @reviews_text.html_safe %></h4>
    </div>
    <%= render 'single_review' %>
  </div>
  <div class="col-md-4">
    <div class="row m0 comments-area">
    	<h2 class="this-area-title">Оставить отзыв</h2>
      <h4 class="this-sub-title">Заполните форму ниже</h4>
    </div>
    <%= form_for Review.new, html: {class:"comment-form row m0"} do |f| %>
      <%= f.text_field :name, placeholder: "Имя *", class: "form-control", required: true %>
      <%= f.text_field :email, placeholder: "Email *", class: "form-control", required: true %>
      <%= f.text_area :text, rows: 8, minlength: 30, placeholder: "Напишите свой отзыв", class: "form-control", required: true %>
      <%= recaptcha_tags %>
      <%= f.submit "Отправить", class: "btn btn-outline center" %>
    <% end %>
  </div>
</div>
<%= render 'shared/footer' %>
<script type="text/javascript">
    var verifyCallback = function(response) {
      alert(response);
    };
    var widgetId1;
    var widgetId2;
    var onloadCallback = function() {
      // Renders the HTML element with id 'example1' as a reCAPTCHA widget.
      // The id of the reCAPTCHA widget is assigned to 'widgetId1'.
      widgetId1 = grecaptcha.render('example1', {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>",
        'theme' : 'light'
      });
      widgetId2 = grecaptcha.render(document.getElementById('example2'), {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>"
      });
      grecaptcha.render('example3', {
        'sitekey' : "<%= Recaptcha.configuration.site_key %>",
        'callback' : verifyCallback,
        'theme' : 'dark'
      });
    };
  </script>